### ISSUE TITLE
Uses plugin template example GUID

### ISSUE THREAD

**Issue by SoundOfScooting** [reeeeemo/Galago#1]
Galago uses the example GUID `com.Windows10CE.Template` from the plugin template instead of its own unique GUID.

On its own, this shouldn't cause any problems, but if another plugin were to also erroneously use this GUID, it would become incompatible with Galago since all plugins must have unqiue GUIDs.

Example fix: `com.reeeeemo.galago`.

**Comment by reeeeemo** [comment]
Fixed, `com.Windows10CE.Template` has changed to `com.reeeeemo.galago`.
