### ISSUE TITLE
libs folder path inconsistent with `galgagoMod.csproj`

### ISSUE THREAD

**Issue by SoundOfScooting** [reeeeemo/Galago#2]
Project expects `<HintPath>..\libs\*.dll</HintPath>`, but `libs` is not in the root folder.
This prevents the project from compiling.

**Comment by reeeeemo** [comment]
Fixed, as included below:
      `<HintPath>..\galagoMod\libs\*.dll</HintPath>`
  Rewrote location of `libs` to `galagoMod\libs`
